### PR TITLE
cell typing workflow and panel app

### PR DESCRIPTION
**Pull request by cvaske**
The `scanpy_decoupler.ipynb` notebook creates an AnnData file `adata-annotated.h5ad` which can be viewed with `app_annotated.py` and viewing the resulting cell type annotations.

To do: expand the panel app to visualize more about the cell typing from the decoupleR algorithm

### CODE REVIEW

**Comment by droumis** [comment]
hitting some errors after running the notebook and trying to serve the app. will try to take a look

**Comment by droumis** [comment]
Alright I think I fixed what I think was a bug, but I don't see any difference in the app. @cvaske can you show me a screenshot or describe what is different? I don't see labels

**Comment by jbednar** [comment]
Also be sure to upload a cleared notebook so that diffs will work in github.  It seems to rely on `quak` and `decoupler` that are only available in pip?

**Comment by cvaske** [comment]
I've been experimenting with `juv` and `quak` (from the same author) and didn't update the environment.yml, apologies! (quak is great but not in conda yet; I'm not yet convinced on juv.)

`decoupler-py` is now in the environment.yml, it just has a different name than in pip. Notebook outputs are cleaned up. I didn't experience the bug with int/str labels in my alternate environment, oddly.

The change is illustrated here (and the default is now `cell_type` too) 
image

The circle plot nicely updates with whatever the categorical labels are, whether they cluster integers or cell type labels.

**Comment by droumis** [comment]
nice work! I'll follow this up with a bit of repo cleanup and probably merge the apps

**Pull request merged**
